name = "radio-backend"
main = "src/index.ts"
compatibility_date = "2024-04-05"

# R2 Bucket Binding
[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "radio-media"
preview_bucket_name = "radio-media-dev"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "radio-db"
database_id = "943bc826-a072-4a26-8eb4-52ca54c243d6" # Replace with actual UUID
preview_database_id = "DB"
